require 'sinatra/activerecord'

require_relative 'account'
require_relative 'trivia'
require_relative 'test'
require_relative 'question'
require_relative 'answer'
require_relative 'game'
require_relative 'account_answer'
require_relative 'account_test'
require_relative 'account_game'
require_relative 'account_trivia'