# frozen_string_literal: true

ruby '2.7.5'

source 'https://rubygems.org'

gem 'multi_json'

github 'sinatra/sinatra' do
  gem 'sinatra'
  gem 'sinatra-contrib'
end

gem 'rake'
gem 'sinatra-activerecord'
gem 'sqlite3'

group :test, :development do
  gem 'rack-test'
  gem 'rspec'
  gem 'rubocop'
end

gem 'simplecov'
